.github/workflows/push.yml, examples/CommanderPRO/CommanderPRO.ino, src/CorsairLightingNodePRO.h, src/LEDController.h
close #36 
* updated firmware versions
* updated port type definition
=> Updated definitions 

.github/workflows/push.yml, src/CLPUtils.cpp
Added more tests for all sketches with more boards.
=> GitHub actions v2

README.md
I noticed a few grammar mistakes in the readme file and fixed them for you.
<3
=> Fixed grammar mistakes in the readme.md file

library.properties, src/FastLEDController.h, src/LEDController.cpp, src/LEDController.h
fixed integer overflow
added validation of internal data
validate the data loaded from EEPROM #44
=> Version 0.6.1

examples/HoodLoader2CLPBridge/CLPUSBSerialBridge.cpp, examples/HoodLoader2UnoMegaController/HoodLoader2UnoMegaController.ino, library.properties, src/CorsairLightingProtocolSerial.cpp, src/CorsairLightingProtocolSerial.h
fixed initialisation order bug on Arduino Uno and Mega
=> Version 0.6.2

examples/CommanderPRO/CommanderPRO.ino, examples/DebugSketch/DebugSketch.ino, examples/HoodLoader2UnoMegaController/HoodLoader2UnoMegaController.ino, examples/RepeatAndScale/RepeatAndScale.ino, examples/SingleStripLightingNodePRO/SingleStripLightingNodePRO.ino, examples/TransformLLFansFormatToStrip/TransformLLFansFormatToStrip.ino, library.properties, src/CorsairLightingNodePRO.h, src/CorsairLightingProtocol.h, src/CorsairLightingProtocolController.cpp, src/CorsairLightingProtocolController.h, src/CorsairLightingProtocolHID.cpp, src/CorsairLightingProtocolHID.h, src/CorsairLightingProtocolSerial.cpp, src/CorsairLightingProtocolSerial.h, src/FanController.h, src/FastLEDController.cpp, src/FastLEDController.h, src/TemperatureController.h
added documentation to CorsairLightingProtocol #50
renamed CorsairLightingProtocol
CorsairLightingProtocol.h is now the central include file
fixed broken DebugSketch
some renamings in FastLEDController
=> Refactorings

examples/AdditionalFeatures/AdditionalFeatures.ino, examples/AdditionalFeatures/board.txt, examples/DebugSketch/DebugSketch.ino, examples/DeviceIDTool/DeviceIDTool.ino, src/CLPAdditionalFeatures.cpp, src/CLPAdditionalFeatures.h, src/CLPUtils.cpp, src/CLPUtils.h, src/CorsairLightingFirmware.cpp, src/CorsairLightingFirmware.h, src/LEDController.cpp, src/LEDController.h
added DeviceID functions to firmware
added reset function for DeviceID and LEDController
=> Added reset function

README.md, examples/AdditionalFeatures/AdditionalFeatures.ino, examples/AdditionalFeatures/board.txt, examples/CommanderPRO/board.txt, examples/DebugSketch/board.txt, examples/HoodLoader2CLPBridge/CLPUSBSerialBridge.cpp, examples/HoodLoader2CLPBridge/CLPUSBSerialBridge.h, examples/HoodLoader2CLPBridge/board.txt, examples/HoodLoader2UnoMegaController/board.txt, examples/LightingNodePRO/board.txt, examples/RepeatAndScale/board.txt, examples/SingleStripLightingNodePRO/board.txt, examples/TransformLLFansFormatToStrip/board.txt, src/CorsairLightingProtocolHID.cpp, src/CorsairLightingProtocolHID.h, src/RawHID.cpp, src/RawHID.h
added serial number as constructor argument to `CorsairLightingProtocolHID` and `CLPUSBSerialBridge`
updated Readme to reflect that change
=> Serial Number can be set from sketch

src/FastLEDControllerUtils.cpp, src/FastLEDControllerUtils.h
added scaleSegment and reverse functions
TODO:
=> Function to scale multiple parts of a strip independently

src/CorsairLightingFirmware.cpp, src/CorsairLightingProtocolHID.cpp, src/FastLEDController.cpp, src/LEDController.cpp
fixed HW lighting for Rainbow channel effect close #46
=> Improve hw playback

.github/workflows/push.yml, examples/LightingNodeCORE/LightingNodeCORE.ino, examples/LightingNodeCORE/board.txt, src/CorsairLightingFirmware.cpp, src/CorsairLightingFirmware.h
=> Added example for Lighting Node CORE

src/FastLEDController.cpp, src/FastLEDController.h, src/FastLEDControllerUtils.cpp, src/FastLEDControllerUtils.h, src/LEDController.cpp, src/LEDController.h
apply gamma correction for video lighting to improve the color of the ambient light.
=> Improve colors for video lighting

README.md, examples/CommanderPRO/PWMFan.cpp, examples/CommanderPRO/PWMFan.h, examples/CommanderPRO/SimpleFanController.cpp, examples/CommanderPRO/SimpleFanController.h, examples/CommanderPRO/ThermistorTemperatureController.h, examples/SingleStripLightingNodePRO/SingleStripLightingNodePRO.ino, src/CLPUtils.h, src/CorsairLightingNodePRO.h, src/CorsairLightingProtocol.h, src/CorsairLightingProtocolController.h, src/CorsairLightingProtocolHID.cpp, src/CorsairLightingProtocolHID.h, src/CorsairLightingProtocolResponse.h, src/CorsairLightingProtocolSerial.cpp, src/CorsairLightingProtocolSerial.h, src/FanController.cpp, src/FanController.h, src/FastLEDController.cpp, src/FastLEDController.h, src/FastLEDControllerUtils.cpp, src/FastLEDControllerUtils.h, src/IFanController.h, src/ILEDController.h, src/ITemperatureController.h, src/LEDController.cpp, src/LEDController.h, src/TemperatureController.h
converted the existing documentation to Javadoc
added documentation to public API close #50
=> Improve the API Documentation

examples/LS100/LS100.ino
Added an optional hardware button to disable the lighting of the LS100 independent of iCUE close #84.
The button should be connected to pin 4 of the Arduino and connect pin 4 to GND if pressed.
=> Added ON/OFF button to LS100

examples/LS100/LS100.ino
reduced the leds on the second channel(first channel in iCUE) close #90
formatted the code of the LS100 sketch
=> fixed out of memory bug in LS100

.github/workflows/push.yml, examples/LS100/LS100.ino, examples/NonAddressable/NonAddressable.ino, examples/NonAddressable/board.txt, extra/doxygen.conf, library.properties
added example for non addressable LED strips #6
added library dependencies in library.properties #89 
fixed out of memory bug in LS100 #90
=> Version 0.9.1

library.properties, src/CorsairLightingProtocolResponse.cpp, src/FanController.cpp, src/FastLEDController.cpp, src/FastLEDControllerUtils.cpp, src/LEDController.cpp, src/RawHID.h, src/TemperatureController.cpp
restrict architectures to avr only (can later be extended) #97
=> improve compatibility with other platforms

.github/workflows/push.yml, examples/AmbientBacklight/AmbientBacklight.ino
added sketch for the ambient backlight guide #68
=> added AmbientBacklight sketch for monitors

.github/workflows/push.yml
Use ArminJo/arduino-test-compile@v2.0.0 action for the GitHub Actions workflow.
Added debug sketch to ci #101
=> Arduino test compile Action

src/FastLEDControllerUtils.cpp
First scale down segments and move them together and then scale the other segments up.
This way no segment information is overwritten and scaling up and down segments can be combined.
close #120
=> fixed down scaling of segments

src/FastLEDController.cpp, src/FastLEDController.h, src/LEDController.cpp, src/LEDController.h
added 30s timeout to SoftwarePlayback when no command is received by the LEDController close #112
This is the same behavior as the real LNC.
=> Added timeout to SoftwarePlayback 

.github/workflows/documentation.yml, .github/workflows/push.yml, examples/AdditionalFeatures/AdditionalFeatures.ino, examples/AmbientBacklight/AmbientBacklight.ino, examples/CommanderPRO/CommanderPRO.ino, examples/DebugSketch/DebugSketch.ino, examples/HoodLoader2UnoMegaController/HoodLoader2UnoMegaController.ino, examples/LS100/LS100.ino, examples/LightingNodeCORE/LightingNodeCORE.ino, examples/LightingNodePRO/LightingNodePRO.ino, examples/RepeatAndScale/RepeatAndScale.ino, examples/SingleStripLightingNodePRO/SingleStripLightingNodePRO.ino, examples/TransformLLFansFormatToStrip/TransformLLFansFormatToStrip.ino
this improves the visibility of the used used led chip type and makes changing it easier #101
=> use WS2812B instead of NEOPIXEL in examples

.github/workflows/push.yml, examples/MultipleFans/MultipleFans.ino
This example show how to connect multiple Fans to the arduino without using a fan hub.
=> Added MultipleFans example

src/FastLEDController.cpp, src/FastLEDController.h
Fixed Hardware Playback brightness control does not work #136 
Fixed the direction of the sequential HW effect
Improved random colors, use predefined color palette from FastLED
=> Refactor FastLEDController

src/FastLEDController.cpp
added second color to visor
improved edges of visor
the moving visor now looks more smooth close #118
=> improve visor hardware lighting effect

src/FastLEDController.cpp, src/LEDController.h
=> clear all color channels

src/FastLEDControllerUtils.cpp
=> fixed scale function when scaling down

.github/CONTRIBUTING.md
=> Added contribution guide

examples/UnitTests/UnitTests.ino, src/FastLEDControllerUtils.cpp
Found a rounding bug in the scaling functions which was resolved with the help of the tests. fixed #163
All the unit tests are in one Sketch and can be uploaded to an Arduino and the results are displayed via the Serial Monitor.
close #144
=> Added Unit tests

examples/AdditionalFeatures/AdditionalFeatures.ino, examples/DebugSketch/DebugSketch.ino, src/CLPUtils.cpp, src/CLPUtils.h
based on simple Arduino loop "FPS" counter - v1.1 by Michael Braverman
=> added FPS counter

examples/UnitTests/UnitTests.ino, src/FastLEDControllerUtils.cpp
=> Fixed scaling boundaries not scaled correctly

.github/workflows/lint.yml, README.md, examples/AdditionalFeatures/AdditionalFeatures.ino, examples/AmbientBacklight/AmbientBacklight.ino, examples/DebugSketch/DebugSketch.ino, examples/UnitTests/UnitTests.ino, extra/doxygen.conf, library.properties, src/CLPUtils.cpp, src/CLPUtils.h, src/FastLEDControllerUtils.cpp, src/FastLEDControllerUtils.h
fixed scaling boundaries not scaled correctly #181
added note to fixIcueBrightness #175
added FPS counter
=> Version 0.14.2

.github/workflows/push.yml, .gitignore
workaround for arduino/arduino-cli#960
updated platform versions
=> set arduino cli version to 0.12.1
